### PR TITLE
Stop modifying submitted password strings.

### PR DESCRIPTION
**Pull request by forevermatt**
Before, we had been doing the following to all input strings (username, password, CSRF value, etc.):
- Ensure it's a string (if not, use an empty string)
- Strip characters with ASCII value less than 32
- Strip backticks ( ` )
- Trim the string

Unfortunately, that meant that a password that ended in a space (or contained a backtick, presumably) could never be used to log in.

This PR changes how passwords are handled so that we merely ensure the given password is a string.

**QUESTION: Should we still be stripping low ASCII characters (< 32)?** Is there any reason to allow / not allow, say, a null-byte (\0) in a password?

### CODE REVIEW

**Review by fillup — APPROVED** [review]

**Comment by fillup** [comment]
In answer to your question; only if they cause a problem in some way, otherwise do we care what the character is?

**Review by Baggerone — APPROVED** [review]
Do we need to remember to test the new version of simplesamlphp before pushing this to a live instance?

**Comment by forevermatt** [comment]
@fillup It may be worth removing null bytes from passwords:
http://php.net/manual/en/function.password-hash.php#118603

However, we should probably do that in ID Broker, so that it applies to all interactions with that password.

**Comment by forevermatt** [comment]
@Baggerone I think ssp-base has been using simplesamlphp `1.14.17` already. Now that you mention it, the composer.lock file here in silauth really only affects local development work.

**Pull request merged**
