### PR TITLE
Return SAML attributes

### PR DESCRIPTION
**Pull request by forevermatt**

### CODE REVIEW

**Review by longrunningprocess — APPROVED** [review]
stoked about the ssp-deps removal!!!

**Review by fillup — APPROVED** [review]

**Comment by forevermatt** [comment]
I'm trying to confirm that, when I interact with this through a browser, it still works (which involves some disentangling from ssp-deps...). Once I've confirmed that, I'll go ahead and merge this.

**Comment by forevermatt** [comment]
@fillup and/or @wcjr, would you mind reviewing the changes I've made to this PR? Once this is merged (and released as something like 3.0.0 or 2.2.0), I think we can then update the `feature/silauth-saml-attrs` branch of **ssp-base** to use that version of silauth and PR/merge it to develop and PR/merge the `feature/silauth-saml-attrs` branch of **ssp-deps** as well, getting is very close to pulling silauth out of the ssp-deps tangle.

**Comment by longrunningprocess** [comment]
I already looked at the most recent changes.  lgtm

**Pull request merged**
